### ISSUE TITLE
SVG not scaling in new FVTT

### ISSUE THREAD

**Issue by HippyCraig** [death-save/pin-cushion#1] opened 2020-04-19 16:09 UTC
Having an issue with Pin Cushion not sizing custom SVG correctly after the update.  Standard ones are fine, the custom ones are not scaling to the size of the box and are too large to display

See image:
![unknown](https://user-images.githubusercontent.com/17074456/79693070-9d78b580-8236-11ea-967d-938c25bf7fb9.png)

**Comment by HippyCraig** [comment] 2020-05-15 23:57
Any update to this?

**Comment by xeth1313** [comment] 2020-05-25 16:26
I am encountering this issue as well. I checked to confirm that I was using the right kind of files, and that the resolution was similar. But I am only able to see the top left portion of any image inserted using Pin Cushion.

**Comment by eclarke12** [comment] 2020-05-30 04:10
@xeth1313 @HippyCraig the issue is that Foundry expects the svg icons to have a `width` and `height` attribute as well as a `viewport` in order to scale correctly. The default icons have these properties set and thus they look correct.

I suggest for custom icons you use the following settings when downloading:
`height="512"`
`width="512"`
`viewport="0 0 512 512"`

I may add some functionality in the future to try to do this in the module, but I'm not sure how complicated it is so I'm marking this as "wontfix" for now

**Comment by HippyCraig** [comment] 2020-05-30 15:25
Ok I got my images from game-icons.net, and if I open the SVG in Notepad++ it shows those values and still I have the issue.

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="height: 512px; width: 512px;"><g class="" transform="translate(0,0)" style="touch-action: none;"><path d="M277.822 18l-33.46 5.637 20.41 20.41 42.12-5.5L457.26 171.332l8.892 52.78-188.006-57.487-8.16 12.145L494 247.27v-65.372L321.695 18h-43.873zm-55.242 9.307L42.775 57.597l-14.457 47.276 195.346 59.732c3.162-2.613 6.453-5.325 12.973-10.673L71.084 103.31l34.695-36.474 2.195-2.31L242.262 46.99l-19.682-19.68zm78.53 30.146l-20.282 2.65 23.832 23.83-32.492 10.833 46.45 11.61-29.983 44.634 154.928 47.373-2.995-17.778-139.46-123.152zm-42.794 5.59L116.626 81.55l-12.427 13.063 149.204 45.625c10.38-8.434 21.128-17.107 30.07-24.093l-75.64-18.91 63.506-21.17-13.024-13.022zM148.13 164.598l-26.595 26.595-11.867-23.734-14.95 44.843-27.23-40.846L53.434 424.46c34.415 5.734 70.622 6.06 109.13-.075L148.13 164.598zm-5.134 43.134l6 202-17.992.536-6-202 17.992-.536zm-69.992.004l17.992.528-6 204-17.992-.528 6-204zM99 208h18v208H99V208zm310 57v42.73c15.296 4.103 50.7 4.374 85 3.99V265h-85zm-21.236 64c-3.1 2.538-6.47 4.89-10.202 6.822-6.376 3.302-14.134 5.18-22.37 3.875-4.783-.758-9.604-2.636-14.467-5.408L327.155 375H439v-46h-51.236zM457 329v46h37v-46h-37zm-185.658 17.377c-8.592 4.21-16.74 8.066-23.008 13.033-5.09 4.035-9.18 8.75-12.11 15.59h78.05l-42.932-28.623zM237.104 393c6.465 18.295 8.62 33.21 8.447 46H247v-46h-9.896zM265 393v46h110v-46H265zm186.73 0l-46.003 46H494v-46h-42.27zM195 442.203c-36.733 4.718-73.905 6.542-111.535 5.186l-3.414 4.45 35.934 6.764-34.38 29.76c38.292 1.366 76.09-.08 113.396-4.42v-41.74zm-174 .014v41.69c11.597 1.292 23.148 2.323 34.656 3.113l20.36-17.624-28.067-5.283 13.704-17.867c-13.492-.93-27.042-2.254-40.654-4.03zM243.748 457c-2.055 11.088-5.47 20.656-8.2 30H311v-30h-67.252zM329 457v30h110v-30H329zm128 0v30h37v-30h-37z" fill="#fff" fill-opacity="1"></path></g></svg>

**Comment by HippyCraig** [comment] 2020-05-30 15:35
I think I got it, I opened it again in Notepad ++ and added to the above:
      viewBox="0 0 512 512" height="512" width="512" style="height: 512px; width: 512px;"
Now they display correctly.

**Comment by eclarke12** [comment] 2020-05-31 19:17
Right. I noticed that the `style` tag was not being respected.

For now I'm going to close this issue as I feel it is "easy" enough to just add the necessary tags externally as I think the effort to fix the svg tags from within the module will be substantial.

**Closed by eclarke12** 2020-05-31 19:17 UTC
Labels: bug, wontfix

**Comment by HippyCraig** [comment] 2020-05-31 20:56
Yea I'm good for now but I did put in a bug in the Discord around this issue. Hopefully its seen and gets addressed moving forward.

Thanks for the the time and help with this :)
