### ISSUE TITLE
Error while mouse-over a pin [PF2E]

### ISSUE THREAD

**Issue by Nerull91** [death-save/pin-cushion#15] opened 2020-06-25 14:42 UTC
![image](https://user-images.githubusercontent.com/29990125/85741543-84760000-b6d0-11ea-9b32-bd9a5af8ec93.png)

**Comment by eclarke12** [comment] 2020-10-06 05:33
Appears to be a duplicate of #11 but it's good to know the game system

**Comment by eclarke12** [comment] 2020-10-07 01:48
Cannot repro. Closing.

**Closed by eclarke12** 2020-10-07 01:48 UTC
Labels: bug
